# KT Part F
# Concepts demonstrated: Java utility usage for dynamic test data
@part-f
@kt-java-utils
Feature: task CRUD create using custom Java utilities

Background:
  # Add the custom Java utility alongside the shared auth setup.
  * url baseUrl
  * def RandomDataUtil = Java.type('examples.util.RandomDataUtil')
  Given path 'api', 'v2', 'auth', 'login'
  And request
    """
    {
      "username": "#(credentials.username)",
      "password": "#(credentials.password)"
    }
    """
  When method post
  Then status 200
  * def authToken = response.token
  * configure headers = { Authorization: '#("Bearer " + authToken)' }

Scenario: create a task with a random suffix generated by Java
  # Generate a unique suffix so repeated runs create distinct titles.
  * def suffix = RandomDataUtil.randomAlphanumeric(6)
  * def title = 'KT java util task ' + suffix
  * def description = 'Task title contains a Java-generated random suffix'
  * def payload = read('classpath:examples/payloads/create-task.json')

  # Use the generated values in the request body.
  Given path 'api', 'v2', 'tasks'
  And request payload
  When method post
  Then status 201
  # Validate the server response with the generated title and description.
  And match response.id == '#number'
  And match response.title == title
  And match response.description == description
  And match response.status == 'TODO'
